# Site Settings
name: H3X0S3
title: H3X0S3 | InfoSec Blog
description: an information security blog which contains a blogs related to hackthebox, tryhackme,web application security.
  Mahmoud Salah.
tags:
  - blog
  - hackthebox
  - web security
  - CTFs
  - tryhackme
  
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: h3x0s3@protonmail.com
# See: https://disqus.com/
disqus_username: H3X0S3
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xoqrvbve


# Social Media Settings
# Remove the item if you don't need it
github_username: H3X0S3
facebook_username: doctor.H3X0S3
twitter_username: H3X0S3
linkedin_username: H3X0S3


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://h3x0s3.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

